// Generated by gencpp from file rbx2_utils/LaunchProcessResponse.msg
// DO NOT EDIT!


#ifndef RBX2_UTILS_MESSAGE_LAUNCHPROCESSRESPONSE_H
#define RBX2_UTILS_MESSAGE_LAUNCHPROCESSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbx2_utils
{
template <class ContainerAllocator>
struct LaunchProcessResponse_
{
  typedef LaunchProcessResponse_<ContainerAllocator> Type;

  LaunchProcessResponse_()
    : process_id()  {
    }
  LaunchProcessResponse_(const ContainerAllocator& _alloc)
    : process_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _process_id_type;
  _process_id_type process_id;





  typedef boost::shared_ptr< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LaunchProcessResponse_

typedef ::rbx2_utils::LaunchProcessResponse_<std::allocator<void> > LaunchProcessResponse;

typedef boost::shared_ptr< ::rbx2_utils::LaunchProcessResponse > LaunchProcessResponsePtr;
typedef boost::shared_ptr< ::rbx2_utils::LaunchProcessResponse const> LaunchProcessResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator1> & lhs, const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator2> & rhs)
{
  return lhs.process_id == rhs.process_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator1> & lhs, const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbx2_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a19d2ed2d6b55934bac7cd67cfed8983";
  }

  static const char* value(const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa19d2ed2d6b55934ULL;
  static const uint64_t static_value2 = 0xbac7cd67cfed8983ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbx2_utils/LaunchProcessResponse";
  }

  static const char* value(const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string process_id\n"
"\n"
;
  }

  static const char* value(const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.process_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaunchProcessResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbx2_utils::LaunchProcessResponse_<ContainerAllocator>& v)
  {
    s << indent << "process_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.process_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBX2_UTILS_MESSAGE_LAUNCHPROCESSRESPONSE_H
